---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps/status
  verbs:
  - get
  - patch
  - update
