# This rule is not used by the project simpleapp-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.yeongki.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simpleapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapp-editor-role
rules:
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps/status
  verbs:
  - get
