# This rule is not used by the project simpleapp-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.yeongki.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simpleapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleapp-admin-role
rules:
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps
  verbs:
  - '*'
- apiGroups:
  - apps.yeongki.dev
  resources:
  - simpleapps/status
  verbs:
  - get
